Repository KOSA-PCMASTER/PCMASTER, pull requests merged in 2023-07, with the labels that each got.

#46 feat(Member): Update Member Info
  src/main/java/kr/or/sw/controller/AuthController.java
  src/main/java/kr/or/sw/controller/MemberController.java
  src/main/java/kr/or/sw/mapper/MemberDAO.java
  src/main/java/kr/or/sw/mapper/MemberDAOImpl.java
  src/main/java/kr/or/sw/model/MemberDTO.java
  src/main/java/kr/or/sw/service/MemberService.java
  src/main/java/kr/or/sw/service/MemberServiceImpl.java
  src/main/resources/mybatis/mapper/memberMapper.xml
  src/main/webapp/WEB-INF/views/auth/register.html
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/layouts/footer.jsp
  src/main/webapp/WEB-INF/views/layouts/header.jsp
  src/main/webapp/WEB-INF/views/layouts/side.jsp
  src/main/webapp/WEB-INF/views/member/member.jsp
  src/main/webapp/WEB-INF/views/member/update.jsp
  src/main/webapp/insert.jsp
  src/main/webapp/js/member.js
  src/main/webapp/main.jsp
  src/main/webapp/order.jsp
  src/main/webapp/stockManage.jsp
Labels: enhancement

#49 fix(stockManage.css, stockManage.jsp)
  src/main/webapp/css/stockManage.css
  src/main/webapp/css/stockManage.scss
  src/main/webapp/index.html
  src/main/webapp/js/passwordSearch1.js
  src/main/webapp/stockManage.jsp
Labels: enhancement

#50 feat(Model): Add DTO
  src/main/java/kr/or/sw/controller/AuthController.java
  src/main/java/kr/or/sw/model/EmpDTO.java
  src/main/java/kr/or/sw/model/MemberDTO.java
  src/main/java/kr/or/sw/model/OrderDTO.java
  src/main/java/kr/or/sw/model/ProductDTO.java
  src/main/java/kr/or/sw/model/ProductStockDTO.java
  src/main/java/kr/or/sw/model/SaleDTO.java
  src/main/java/kr/or/sw/model/StockDTO.java
  src/main/resources/sql/member.sql
  src/main/webapp/WEB-INF/views/member/update.jsp
  src/main/webapp/indexManager.html
Labels: enhancement

#51 Add Controller, Service, DAO, Mapper
  src/main/java/kr/or/sw/controller/AuthController.java
  src/main/java/kr/or/sw/controller/HomeController.java
  src/main/java/kr/or/sw/controller/MemberController.java
  src/main/java/kr/or/sw/controller/ProductController.java
  src/main/java/kr/or/sw/controller/StockController.java
  src/main/java/kr/or/sw/mapper/ProductDAO.java
  src/main/java/kr/or/sw/mapper/ProductDAOImpl.java
  src/main/java/kr/or/sw/mapper/StockDAO.java
  src/main/java/kr/or/sw/mapper/StockDAOImpl.java
  src/main/java/kr/or/sw/service/ProductService.java
  src/main/java/kr/or/sw/service/ProductServiceImpl.java
  src/main/java/kr/or/sw/service/StockService.java
  src/main/java/kr/or/sw/service/StockServiceImpl.java
  src/main/resources/mybatis/mapper/productMapper.xml
  src/main/resources/mybatis/mapper/stockMapper.xml
  src/main/resources/mybatis/mybatis-config.xml
Labels: enhancement

#52 refactor(Service)
  src/main/java/kr/or/sw/controller/AuthController.java
  src/main/java/kr/or/sw/controller/HomeController.java
  src/main/java/kr/or/sw/controller/MemberController.java
  src/main/java/kr/or/sw/controller/ProductController.java
  src/main/java/kr/or/sw/controller/StockController.java
  src/main/java/kr/or/sw/service/AuthService.java
  src/main/java/kr/or/sw/service/AuthServiceImpl.java
  src/main/java/kr/or/sw/service/MemberService.java
  src/main/java/kr/or/sw/service/MemberServiceImpl.java
  src/main/java/kr/or/sw/service/ProductService.java
  src/main/java/kr/or/sw/service/ProductServiceImpl.java
  src/main/java/kr/or/sw/service/Service.java
  src/main/java/kr/or/sw/service/StockService.java
  src/main/java/kr/or/sw/service/StockServiceImpl.java
Labels: enhancement

#53 docs(DDL): Add DDL
  src/main/java/kr/or/sw/service/ProductService.java
  src/main/java/kr/or/sw/service/ProductServiceImpl.java
  src/main/java/kr/or/sw/service/StockServiceImpl.java
  src/main/resources/sql/member.sql
  src/main/resources/sql/order.sql
  src/main/resources/sql/product.sql
  src/main/resources/sql/product_stock.sql
  src/main/resources/sql/sale.sql
  src/main/resources/sql/stock.sql
Labels: documentation

#55 feat(style): add client main page
  src/main/webapp/css/info.css
  src/main/webapp/css/info.scss
  src/main/webapp/info.jsp
Labels: enhancement

#60 feat(member): add birthDate
  src/main/java/kr/or/sw/controller/AuthController.java
  src/main/java/kr/or/sw/controller/MemberController.java
  src/main/java/kr/or/sw/controller/ProductController.java
  src/main/java/kr/or/sw/controller/StockController.java
  src/main/java/kr/or/sw/model/MemberDTO.java
  src/main/java/kr/or/sw/service/AuthServiceImpl.java
  src/main/resources/mybatis/mapper/authMapper.xml
  src/main/resources/sql/member.sql
  src/main/webapp/WEB-INF/views/auth/register.html
  src/main/webapp/WEB-INF/views/customer.jsp
  src/main/webapp/js/register.js
Labels: enhancement

#62 feat(add reset password)
  src/main/java/kr/or/sw/controller/AuthController.java
  src/main/java/kr/or/sw/mapper/AuthDAO.java
  src/main/java/kr/or/sw/mapper/AuthDAOImpl.java
  src/main/java/kr/or/sw/service/AuthService.java
  src/main/java/kr/or/sw/service/AuthServiceImpl.java
  src/main/resources/mybatis/mapper/authMapper.xml
  src/main/webapp/WEB-INF/views/auth/findPassword.html
  src/main/webapp/WEB-INF/views/auth/register.html
  src/main/webapp/css/passwordSearch.css
  src/main/webapp/css/passwordSearch.scss
  src/main/webapp/css/passwordSearch2.css
  src/main/webapp/css/passwordSearch2.scss
  src/main/webapp/docs/passwordSearch1.html
  src/main/webapp/docs/passwordSearch2.html
  src/main/webapp/js/findPassword.js
  src/main/webapp/js/passwordSearch1.js
  src/main/webapp/js/passwordSearch2.js
  src/main/webapp/js/register.js
  src/main/webapp/js/validation.js
Labels: enhancement

#68 feat: add preview image in product insert page
  src/main/webapp/WEB-INF/views/layouts/side.jsp
  src/main/webapp/WEB-INF/views/product/productInsert.jsp
  src/main/webapp/css/insert.css
  src/main/webapp/css/insert.scss
  src/main/webapp/js/productInsert.js
Labels: enhancement

#71 docs(ddl): update ddl
  src/main/java/kr/or/sw/model/EmpDTO.java
  src/main/java/kr/or/sw/model/ProductDTO.java
  src/main/resources/sql/emp.sql
  src/main/resources/sql/member.sql
  src/main/resources/sql/order.sql
  src/main/resources/sql/product.sql
  src/main/resources/sql/product_stock.sql
  src/main/resources/sql/sale.sql
  src/main/resources/sql/stock.sql
  src/main/webapp/WEB-INF/views/home.jsp
Labels: documentation

#74 refactor(dao): increase cohesion
  src/main/java/kr/or/sw/controller/ProductController.java
  src/main/java/kr/or/sw/mapper/AuthDAO.java
  src/main/java/kr/or/sw/mapper/AuthDAOImpl.java
  src/main/java/kr/or/sw/mapper/MemberDAO.java
  src/main/java/kr/or/sw/mapper/MemberDAOImpl.java
  src/main/java/kr/or/sw/mapper/ProductDAO.java
  src/main/java/kr/or/sw/mapper/ProductDAOImpl.java
  src/main/java/kr/or/sw/model/ProductDTO.java
  src/main/java/kr/or/sw/model/ProductImgDTO.java
  src/main/java/kr/or/sw/service/AuthServiceImpl.java
  src/main/java/kr/or/sw/service/MemberServiceImpl.java
  src/main/java/kr/or/sw/service/ProductServiceImpl.java
  src/main/java/kr/or/sw/service/Service.java
Labels: enhancement

#79 feat(product): insert product info with image
  src/main/java/kr/or/sw/controller/ProductController.java
  src/main/java/kr/or/sw/mapper/ProductDAO.java
  src/main/java/kr/or/sw/mapper/ProductDAOImpl.java
  src/main/java/kr/or/sw/model/ProductDTO.java
  src/main/java/kr/or/sw/model/ProductImgDTO.java
  src/main/java/kr/or/sw/service/ProductServiceImpl.java
  src/main/resources/mybatis/mapper/productMapper.xml
  src/main/resources/sql/emp.sql
  src/main/resources/sql/member.sql
  src/main/resources/sql/order.sql
  src/main/resources/sql/product.sql
  src/main/resources/sql/productImg.sql
  src/main/resources/sql/product_stock.sql
  src/main/resources/sql/sale.sql
  src/main/resources/sql/stock.sql
  src/main/webapp/WEB-INF/views/product/productInsert.jsp
  src/main/webapp/css/customer.css
Labels: enhancement

#82 fix: fix ProductController's redirect URL
  src/main/java/kr/or/sw/controller/ProductController.java
  src/main/webapp/WEB-INF/views/product/productInsert.jsp
Labels: good first issue

#87 feat(product): delete product
  src/main/java/kr/or/sw/controller/MemberController.java
  src/main/java/kr/or/sw/controller/ProductController.java
  src/main/java/kr/or/sw/mapper/ProductDAO.java
  src/main/java/kr/or/sw/mapper/ProductDAOImpl.java
  src/main/java/kr/or/sw/model/MemberDTO.java
  src/main/java/kr/or/sw/model/ProductDTO.java
  src/main/java/kr/or/sw/service/ProductServiceImpl.java
  src/main/resources/mybatis/mapper/productMapper.xml
  src/main/resources/mybatis/mapper/stockMapper.xml
  src/main/resources/sql/product.sql
  src/main/webapp/WEB-INF/views/layouts/header.jsp
  src/main/webapp/WEB-INF/views/product/productList.jsp
  src/main/webapp/js/product.js
Labels: enhancement

#88 feat: enhance customer page
  src/main/webapp/WEB-INF/views/customer.jsp
  src/main/webapp/WEB-INF/views/product/productInsert.jsp
  src/main/webapp/js/customer.js
Labels: enhancement

#89 feat(product): add relative upload path
  src/main/java/kr/or/sw/controller/AuthController.java
  src/main/java/kr/or/sw/controller/CustomerController.java
  src/main/java/kr/or/sw/controller/HomeController.java
  src/main/java/kr/or/sw/controller/StockController.java
  src/main/java/kr/or/sw/mapper/CustomerDAO.java
  src/main/java/kr/or/sw/mapper/StockDAO.java
  src/main/java/kr/or/sw/mapper/StockDAOImpl.java
  src/main/java/kr/or/sw/model/ProductImgDTO.java
  src/main/java/kr/or/sw/model/StockDTO.java
  src/main/java/kr/or/sw/service/AuthService.java
  src/main/java/kr/or/sw/service/CustomerService.java
  src/main/java/kr/or/sw/service/ProductService.java
  src/main/java/kr/or/sw/service/ProductServiceImpl.java
  src/main/java/kr/or/sw/service/StockService.java
  src/main/java/kr/or/sw/service/StockServiceImpl.java
  src/main/resources/mybatis/mapper/memberMapper.xml
  src/main/resources/mybatis/mapper/productMapper.xml
  src/main/resources/sql/docs/home.html
  src/main/resources/sql/member.sql
  src/main/resources/sql/productImg.sql
  src/main/resources/sql/sale.sql
  src/main/resources/sql/stock.sql
  src/main/webapp/WEB-INF/views/customer.jsp
  src/main/webapp/WEB-INF/views/stock/stockInsert.jsp
  src/main/webapp/WEB-INF/views/stock/stockList.jsp
  src/main/webapp/WEB-INF/views/stock/stockUpdate.jsp
  src/main/webapp/js/stock.js
Labels: enhancement

#93 feat(product): update product
  pom.xml
  src/main/java/kr/or/sw/controller/ProductController.java
  src/main/java/kr/or/sw/controller/StockController.java
  src/main/java/kr/or/sw/mapper/ProductDAO.java
  src/main/java/kr/or/sw/mapper/ProductDAOImpl.java
  src/main/java/kr/or/sw/mapper/StockDAO.java
  src/main/java/kr/or/sw/mapper/StockDAOImpl.java
  src/main/java/kr/or/sw/model/ProductDTO.java
  src/main/java/kr/or/sw/model/ProductImgDTO.java
  src/main/java/kr/or/sw/model/StockDTO.java
  src/main/java/kr/or/sw/service/ProductServiceImpl.java
  src/main/java/kr/or/sw/service/StockServiceImpl.java
  src/main/resources/mybatis/mapper/productMapper.xml
  src/main/resources/mybatis/mapper/stockMapper.xml
  src/main/webapp/WEB-INF/views/customer.jsp
  src/main/webapp/WEB-INF/views/product/productInsert.jsp
  src/main/webapp/css/customer.scss
  src/main/webapp/js/customer.js
Labels: enhancement

#102 feat(customer): insert sale
  pom.xml
  src/main/java/kr/or/sw/controller/BalanceController.java
  src/main/java/kr/or/sw/controller/StockController.java
  src/main/java/kr/or/sw/mapper/CustomerDAO.java
  src/main/java/kr/or/sw/mapper/CustomerDAOImpl.java
  src/main/java/kr/or/sw/model/BalanceVO.java
  src/main/java/kr/or/sw/model/EmpDTO.java
  src/main/java/kr/or/sw/model/OrderVO.java
  src/main/java/kr/or/sw/model/ProductDTO.java
  src/main/java/kr/or/sw/model/Product_Stock_Map.java
  src/main/java/kr/or/sw/model/SaleVO.java
  src/main/java/kr/or/sw/model/Sale_Product_Map.java
  src/main/java/kr/or/sw/model/StockDTO.java
  src/main/java/kr/or/sw/service/CustomerServiceImpl.java
  src/main/java/kr/or/sw/service/StockServiceImpl.java
  src/main/resources/log4j.xml
  src/main/resources/mybatis/mapper/customerMapper.xml
  src/main/resources/mybatis/mapper/productMapper.xml
  src/main/resources/mybatis/mapper/stockMapper.xml
  src/main/resources/sql/balance.sql
  src/main/resources/sql/emp.sql
  src/main/resources/sql/member.sql
  src/main/resources/sql/order.sql
  src/main/resources/sql/product.sql
  src/main/resources/sql/productImg.sql
  src/main/resources/sql/product_stock.sql
  src/main/resources/sql/sale.sql
  src/main/resources/sql/sale_product.sql
  src/main/resources/sql/stock.sql
  src/main/webapp/WEB-INF/views/product/productList.jsp
  src/main/webapp/WEB-INF/views/stock/stockInsert.jsp
  src/main/webapp/WEB-INF/views/stock/stockList.jsp
  src/main/webapp/WEB-INF/views/stock/stockUpdate.jsp
  src/main/webapp/css/customer.scss
  src/main/webapp/css/main.css.map
  src/main/webapp/css/main.scss
  src/main/webapp/js/customer.js
  src/main/webapp/js/index.js
Labels: enhancement

#104 add admin login
  src/main/java/kr/or/sw/controller/AuthController.java
  src/main/java/kr/or/sw/controller/ProductController.java
  src/main/java/kr/or/sw/mapper/AuthDAO.java
  src/main/java/kr/or/sw/mapper/AuthDAOImpl.java
  src/main/java/kr/or/sw/mapper/CustomerDAOImpl.java
  src/main/java/kr/or/sw/mapper/ProductDAO.java
  src/main/java/kr/or/sw/mapper/ProductDAOImpl.java
  src/main/java/kr/or/sw/model/SaleVO.java
  src/main/java/kr/or/sw/service/AuthService.java
  src/main/java/kr/or/sw/service/AuthServiceImpl.java
  src/main/java/kr/or/sw/service/ProductService.java
  src/main/java/kr/or/sw/service/ProductServiceImpl.java
  src/main/resources/mybatis/mapper/authMapper.xml
  src/main/resources/mybatis/mapper/customerMapper.xml
  src/main/resources/mybatis/mapper/productMapper.xml
  src/main/resources/sql/sale.sql
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/product/productOrder.jsp
  src/main/webapp/css/order.css
  src/main/webapp/css/order.scss
  src/main/webapp/index.html
  src/main/webapp/js/order.js
Labels: enhancement

#106 productupdate error fix
  src/main/java/kr/or/sw/controller/ProductController.java
  src/main/java/kr/or/sw/service/ProductServiceImpl.java
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/product/productList.jsp
  src/main/webapp/WEB-INF/views/product/productUpdate.jsp
  src/main/webapp/css/product.css
  src/main/webapp/css/product.scss
  src/main/webapp/js/productInsert.js
  src/main/webapp/js/validation.js
Labels: enhancement

#107 feat: add alert message
  src/main/java/kr/or/sw/controller/AuthController.java
  src/main/java/kr/or/sw/service/AuthServiceImpl.java
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/layouts/side.jsp
  src/main/webapp/css/main.css
  src/main/webapp/css/main.css.map
  src/main/webapp/css/main.scss
  src/main/webapp/css/product.css
  src/main/webapp/index.html
  src/main/webapp/js/customer.js
Labels: enhancement

#110 refactor(customer): move from controller to service
  src/main/java/kr/or/sw/controller/CustomerController.java
  src/main/java/kr/or/sw/service/CustomerServiceImpl.java
  src/main/resources/sql/order.sql
  src/main/resources/sql/product.sql
  src/main/resources/sql/sale.sql
  src/main/resources/sql/stock.sql
Labels: documentation

#119 add cusomer resign
  src/main/java/kr/or/sw/controller/CustomerController.java
  src/main/java/kr/or/sw/mapper/AuthDAO.java
  src/main/java/kr/or/sw/mapper/CustomerDAO.java
  src/main/java/kr/or/sw/mapper/CustomerDAOImpl.java
  src/main/java/kr/or/sw/service/CustomerServiceImpl.java
  src/main/webapp/WEB-INF/views/customer.jsp
  src/main/webapp/js/customer.js
Labels: enhancement

#124 feat: done update customer's self
  src/main/java/kr/or/sw/mapper/MemberDAO.java
  src/main/java/kr/or/sw/mapper/MemberDAOImpl.java
  src/main/java/kr/or/sw/service/CustomerServiceImpl.java
  src/main/resources/mybatis/mapper/memberMapper.xml
  src/main/webapp/WEB-INF/views/customer.jsp
  src/main/webapp/js/customer.js
Labels: enhancement

#125 stockOrder recover and title update
  src/main/java/kr/or/sw/controller/StockController.java
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/layouts/header.jsp
  src/main/webapp/WEB-INF/views/stock/stockList.jsp
  src/main/webapp/WEB-INF/views/stock/stockOrder.jsp
  src/main/webapp/index.html
  src/main/webapp/js/stock.js
Labels: enhancement

#126 feat(product): update recipe
  src/main/java/kr/or/sw/mapper/CustomerDAOImpl.java
  src/main/java/kr/or/sw/mapper/ProductDAOImpl.java
  src/main/java/kr/or/sw/service/ProductServiceImpl.java
  src/main/resources/mybatis/mapper/productMapper.xml
Labels: enhancement

#127 feat(product): decrease stock
  src/main/resources/mybatis/mapper/customerMapper.xml
Labels: enhancement

#128 feat: add filter the product which not enroll ingredients
  src/main/java/kr/or/sw/model/ProductDTO.java
  src/main/java/kr/or/sw/service/AuthServiceImpl.java
  src/main/resources/mybatis/mapper/customerMapper.xml
  src/main/resources/mybatis/mapper/productMapper.xml
  src/main/webapp/WEB-INF/views/customer.jsp
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/WEB-INF/views/product/productList.jsp
  src/main/webapp/WEB-INF/views/product/productSearchIngredient.jsp
Labels: enhancement

#129 refactor(remove quantity, stockdate in insert stock page):
  src/main/java/kr/or/sw/model/StockVO.java
  src/main/java/kr/or/sw/service/StockServiceImpl.java
  src/main/resources/mybatis/mapper/stockMapper.xml
  src/main/webapp/WEB-INF/views/stock/stockInsert.jsp
Labels: enhancement

#130 feat(stock): order stock
  src/main/java/kr/or/sw/controller/AuthController.java
  src/main/java/kr/or/sw/controller/CustomerController.java
  src/main/java/kr/or/sw/controller/StockController.java
  src/main/java/kr/or/sw/mapper/AuthDAO.java
  src/main/java/kr/or/sw/mapper/CustomerDAO.java
  src/main/java/kr/or/sw/mapper/CustomerDAOImpl.java
  src/main/java/kr/or/sw/mapper/StockDAO.java
  src/main/java/kr/or/sw/mapper/StockDAOImpl.java
  src/main/java/kr/or/sw/model/SaleVO.java
  src/main/java/kr/or/sw/model/StockVO.java
  src/main/java/kr/or/sw/service/BalanceServiceImpl.java
  src/main/java/kr/or/sw/service/CustomerServiceImpl.java
  src/main/java/kr/or/sw/service/StockService.java
  src/main/java/kr/or/sw/service/StockServiceImpl.java
  src/main/resources/mybatis/mapper/productMapper.xml
  src/main/resources/mybatis/mapper/stockMapper.xml
  src/main/webapp/WEB-INF/views/customer.jsp
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/layouts/header.jsp
  src/main/webapp/WEB-INF/views/layouts/nav.jsp
  src/main/webapp/WEB-INF/views/product/productSearchIngredient.jsp
  src/main/webapp/WEB-INF/views/stock/stockInsert.jsp
  src/main/webapp/WEB-INF/views/stock/stockList.jsp
  src/main/webapp/WEB-INF/views/stock/stockOrder.jsp
  src/main/webapp/css/customer.scss
  src/main/webapp/css/product.scss
  src/main/webapp/index.html
  src/main/webapp/js/customer.js
  src/main/webapp/js/order.js
  src/main/webapp/js/product.js
  src/main/webapp/js/stock.js
Labels: enhancement

#131 Update README.md
  README.md
Labels: documentation

#132 add role in readme
  README.md
Labels: documentation

#133 fix: product's amount in shopping cart is now readonly
  src/main/webapp/index.html
  src/main/webapp/js/customer.js
Labels: bug

#134 fix bugs
  src/main/resources/mybatis/mapper/memberMapper.xml
  src/main/webapp/js/productIngredient.js
Labels: bug

#135 bug fix and add validation
  src/main/webapp/WEB-INF/views/auth/register.html
  src/main/webapp/WEB-INF/views/member/memberUpdate.jsp
  src/main/webapp/WEB-INF/views/product/productSearchIngredient.jsp
  src/main/webapp/js/memberUpdate.js
Labels: bug

#138 login page design
  src/main/webapp/css/index.css
  src/main/webapp/css/index.scss
  src/main/webapp/images/food.png
  src/main/webapp/images/home.png
  src/main/webapp/index.html
Labels: enhancement

#139 feat(product): renewal product quantity
  src/main/resources/mybatis/mapper/productMapper.xml
  src/main/resources/mybatis/mapper/stockMapper.xml
  src/main/resources/sql/balance.sql
  src/main/resources/sql/emp.sql
  src/main/resources/sql/member.sql
  src/main/resources/sql/order.sql
  src/main/resources/sql/product.sql
  src/main/resources/sql/productImg.sql
  src/main/resources/sql/product_stock.sql
  src/main/resources/sql/sale.sql
  src/main/resources/sql/stock.sql
  src/main/webapp/js/productIngredient.js
Labels: enhancement

#141 fix login page
  src/main/webapp/WEB-INF/views/auth/findPassword.html
  src/main/webapp/WEB-INF/views/auth/register.html
  src/main/webapp/css/findPassword.css
  src/main/webapp/css/findPassword.scss
  src/main/webapp/css/index.css
  src/main/webapp/css/index.scss
  src/main/webapp/css/register.css
  src/main/webapp/css/register.scss
Labels: enhancement

#143 fix: product amount change tag type div from input
  src/main/webapp/css/customer.css
  src/main/webapp/css/customer.scss
  src/main/webapp/js/customer.js
Labels: bug

#147 feat: add assets in balance page
  src/main/java/kr/or/sw/controller/BalanceController.java
  src/main/java/kr/or/sw/mapper/BalanceDAO.java
  src/main/java/kr/or/sw/mapper/BalanceDAOImpl.java
  src/main/java/kr/or/sw/service/BalanceService.java
  src/main/java/kr/or/sw/service/BalanceServiceImpl.java
  src/main/resources/mybatis/mapper/balanceMapper.xml
  src/main/webapp/WEB-INF/views/balance/balance.jsp
Labels: enhancement

#149 feat(auth): hash answer
  src/main/java/kr/or/sw/controller/AuthController.java
  src/main/java/kr/or/sw/service/AuthService.java
  src/main/java/kr/or/sw/service/AuthServiceImpl.java
  src/main/java/kr/or/sw/service/CustomerServiceImpl.java
  src/main/java/kr/or/sw/service/ProductServiceImpl.java
  src/main/java/kr/or/sw/service/StockServiceImpl.java
  src/main/resources/mybatis/mapper/authMapper.xml
  src/main/resources/mybatis/mapper/customerMapper.xml
  src/main/webapp/js/findPassword.js
Labels: enhancement

#150 fix: fix add ingredient sort bug
  src/main/java/kr/or/sw/service/ProductServiceImpl.java
  src/main/webapp/js/productIngredient.js
Labels: bug

#151 feat(balance): add accumulated fields
  src/main/resources/mybatis/mapper/customerMapper.xml
  src/main/resources/mybatis/mapper/stockMapper.xml
  src/main/resources/sql/balance.sql
Labels: enhancement

#154 fix: fix menu's hover view position from absolute to relative
  src/main/webapp/css/customer.css
  src/main/webapp/css/customer.scss
  src/main/webapp/js/customer.js
Labels: bug

#157 update README.md
  README.md
  src/main/resources/sql/balance.sql
  src/main/resources/sql/emp.sql
  src/main/resources/sql/member.sql
  src/main/resources/sql/order.sql
  src/main/resources/sql/product.sql
  src/main/resources/sql/productImg.sql
  src/main/resources/sql/product_stock.sql
  src/main/resources/sql/sale.sql
  src/main/resources/sql/stock.sql
Labels: documentation

#158 docs: add comment in customer.js
  src/main/webapp/js/customer.js
Labels: documentation

#160 Update README.md
  README.md
  src/main/java/kr/or/sw/mapper/CustomerDAOImpl.java
  src/main/java/kr/or/sw/service/BalanceService.java
  src/main/resources/mybatis/mapper/balanceMapper.xml
  src/main/resources/mybatis/mapper/customerMapper.xml
  src/main/resources/mybatis/mapper/memberMapper.xml
  src/main/resources/mybatis/mapper/productMapper.xml
  src/main/resources/mybatis/mapper/stockMapper.xml
  src/main/webapp/WEB-INF/views/balance/balance.jsp
  src/main/webapp/css/customer.scss
Labels: documentation

#162 fix: fix paging
  src/main/webapp/WEB-INF/views/balance/balance.jsp
  src/main/webapp/WEB-INF/views/member/member.jsp
  src/main/webapp/WEB-INF/views/product/productList.jsp
  src/main/webapp/WEB-INF/views/stock/stockList.jsp
Labels: bug
